# Generated by Django 4.1.5 on 2023-05-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uploadtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtask',
            name='job_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
